permalink: pretty
highlighter: pygments

exclude: [todo.txt, files/, mirror/, README.textile]

domain: lukasz.dk
title: Lukasz.dk
author: Lukasz
email: mail@lukasz.dk

ftp_host: lukasz.dk
ftp_dir: /public_html